name: auto-pr

on:
  push: 
    branches:
      - main
      - feature/*

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MJ_PAT_TOKEN }}@github.com/jangminjuu/mj-test.git

      - name: Make a dummy change to trigger a PR
        run: |
          echo "Automated update at $(date '+%Y-%m-%d %H:%M:%S')" >> README.md
          echo "---" >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MJ_PAT_TOKEN }}
          commit-message: "docs: Automated README update"
          title: "Automated PR: README.md Update"
          body: |
            이 Pull Request는 GitHub Actions에 의해 자동으로 생성되었습니다.
            
            * 변경 사항: README.md 파일에 타임스탬프가 추가되었습니다.
            
            AI 요약은 이 PR이 생성된 후 별도로 추가됩니다.
          branch: "auto-pr-test-${{ github.run_number }}"
          base: main
          delete-branch: true
          labels: "auto-pr"
