name: PR AI Summary

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  summarize_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate diff

      - name: Set up Python
        id: setup-python-env
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          "${{ steps.setup-python-env.outputs.python-path }}/bin/python" -m pip install --upgrade pip
          "${{ steps.setup-python-env.outputs.python-path }}/bin/pip" install --no-cache-dir google-generativeai PyGithub

      - name: Get PR Details and Summarize
        run: |
          "${{ steps.setup-python-env.outputs.python-path }}/bin/python" .github/scripts/summarize_pr.py
           
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}